### ISSUE TITLE
Exception when ipaddress library is used

### ISSUE THREAD

**Issue by schultz9999** [uber/mutornadomon#18]
Seeing this when executing a request:

```Uncaught exception
Traceback (most recent call last):
  File "/home/uber/ump/env/local/lib/python2.7/site-packages/tornado/http1connection.py", line 238, in _read_message
    delegate.finish()
  File "/home/uber/ump/env/local/lib/python2.7/site-packages/tornado/httpserver.py", line 289, in finish
    self.delegate.finish()
  File "/home/uber/ump/env/local/lib/python2.7/site-packages/tornado/web.py", line 2022, in finish
    self.execute()
  File "/home/uber/ump/env/local/lib/python2.7/site-packages/tornado/web.py", line 2043, in execute
    transforms = [t(self.request) for t in self.application.transforms]
  File "/home/uber/ump/env/local/lib/python2.7/site-packages/mutornadomon/collectors/web.py", line 25, in _request
    if net.is_local_address(request.remote_ip):
  File "/home/uber/ump/env/local/lib/python2.7/site-packages/mutornadomon/net.py", line 34, in is_local_address
    ip = IP(ip)
  File "/home/uber/ump/env/local/lib/python2.7/site-packages/ipaddress.py", line 163, in ip_address
    ' a unicode object?' % address)
AddressValueError: '127.0.0.1' does not appear to be an IPv4 or IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?```

Tracked down to net.py `import` statement:
```
try:
    import ipaddress
    Network = ipaddress.ip_network
    IP = ipaddress.ip_address
except ImportError:
    import ipcalc
    Network = ipcalc.Network
    IP = ipcalc.IP
```

If I have `ipaddress` installed, I see the error above and if `ipcalc` is used, it's all good.

**Comment by Roguelazer** [comment]
Are you on Python 2 or Python 3?

**Comment by schultz9999** [comment]
Python 2.7.10.

**Comment by blampe** [comment]
Was this on 0.3.2? 0.3.3 should have fixed this with #15.
